# Node.js LTS(최신 장기 지원 버전) 이미지 사용하여 빌드 환경 설정
FROM node AS build

# 작업 디렉토리 설정 (모든 명령이 실행될 기본 폴더)
WORKDIR /app

# package.json과 package-lock.json 파일을 컨테이너로 복사
COPY package.json package-lock.json ./

# 의존성 설치 (package.json 기반으로 npm 패키지 다운로드)
RUN npm install

# 전체 프로젝트 파일을 컨테이너 내부로 복사
COPY . .

# 빌드 실행 (React 같은 프론트엔드 프로젝트의 정적 파일 생성)
RUN npm run build


# Nginx 최신 안정화 버전의 Alpine 기반 이미지 사용
FROM nginx

# COPY nginx.conf /etc/nginx/conf.d/default.conf
# 빌드된 정적 파일을 Nginx의 기본 html 폴더로 복사
COPY --from=build /app/dist /usr/share/nginx/html

COPY ./templates /etc/nginx/templates
# 컨테이너에서 80번 포트 열어두기 (HTTP 요청 허용)
EXPOSE 80
 
# Nginx 실행 (백그라운드 실행 방지)
CMD [ "nginx", "-g", "daemon off;" ]
